//Category related action constants
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERR = 'GET_CATEGORIES_ERR';
export const GET_ALL_FOR_CATEGORY_SUCCESS = "GET_ALL_FOR_CATEGORY_SUCCESS";
export const GET_ALL_FOR_CATEGORY_ERR = "GET_ALL_FOR_CATEGORY_ERR";
