//Category related action constants
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERR = 'GET_CATEGORIES_ERR';
export const GET_ALL_FOR_CATEGORY_SUCCESS = "GET_ALL_FOR_CATEGORY_SUCCESS";
export const GET_ALL_FOR_CATEGORY_ERR = "GET_ALL_FOR_CATEGORY_ERR";



export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERR = 'GET_ALL_POSTS_ERR';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERR = 'GET_POST_ERR';
export const CLEAR_FORM_POST = 'CLEAR_FORM_POST';
export const DELETE_POST = 'DELETE_POST';
export const VOTE_ON_POST = 'VOTE_ON_POST';
